### ISSUE TITLE
Broken example with onehotbatch in docs

### ISSUE THREAD

**Issue by natema** [FluxML/Flux.jl#1214]
In the [Batches section of the One-Hot Encoding doc](https://fluxml.ai/Flux.jl/stable/data/onehot/#Batches-1), `onehotbatch` returns a boolean matrix, while currently (v0.10.4), the output is a binary matrix which, by the way, it is not accepted by the subsequent call to `onecold`:
```
julia> Flux.onehotbatch([:b, :a, :b], [:a, :b, :c])
3×3 Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}:
 0  1  0
 1  0  1
 0  0  0

julia> Flux.onecold(ans, [:a, :b, :c])
ERROR: MethodError: no method matching |(::Int64, ::Symbol)
```

**Comment by lassepe** [comment]
Maybe I am getting you wrong but it seems fixed in the [current docs](https://fluxml.ai/Flux.jl/stable/data/onehot/#Flux.onehot).

As for `Flux.onecold`: it  can not handle batches in it's current implementation. You would have to implement something like `onecoldbatch`.

**Comment by natema** [comment]
🤔 I still see the issue with `onehotbatch` in the [Batches section](https://fluxml.ai/Flux.jl/stable/data/onehot/#Batches-1), where `onecold` is shown to handle batches. I opened the link in a private tab to avoid seeing a cached version of the page. Here's a screenshot: 
![image](https://user-images.githubusercontent.com/2920162/85038091-767f2700-b186-11ea-8bbf-2d3dadd13be7.png)

**Comment by lassepe** [comment]
Oh I see. I was looking at the docs for the Function. The introductory text in the `Batches` chapter is not a `jldoctest` which is probably the reason no one has noticed.

I guess `onecold` was intended to work with batched data. https://github.com/FluxML/Flux.jl/pull/764 actually would fix this.

**Comment by CarloLucibello** [comment]
this works in v0.11.2
```julia
julia> using Flux

julia> Flux.onehotbatch([:b, :a, :b], [:a, :b, :c])
3×3 Flux.OneHotMatrix{Array{Flux.OneHotVector,1}}:
 0  1  0
 1  0  1
 0  0  0

julia> Flux.onecold(ans, [:a, :b, :c])
3-element Array{Symbol,1}:
 :b
 :a
 :b
```
