### ISSUE TITLE
CUDNN BatchNorm with relu doesn't apply relu (when using CuArrays) 

### ISSUE THREAD

**Issue by GantZA** [FluxML/Flux.jl#760]
I'm using Julia 1.1 and I think I've found a bug where the relu function isn't applied after BatchNorm but only when I have `using CuArrays`. Here's simple code where I get the error:
```
using Flux
using CuArrays

bn = BatchNorm(10) |> gpu
bn_relu = BatchNorm(10, relu) |> gpu

test_img = rand(3,3,10,3) |> gpu

a = bn(test_img)
b = bn_relu(test_img)

minimum(a) #Should be negative
minimum(b) #Should be greater than or equal to 0

```

And if I remove the `using CuArrays` line it works. I know I don't need to CuArrays package but I was using it in another script and suddenly relu wasn't working properly. I just took me a while to figure out what was causing it.

Is this a bug or is it my mistake for using CuArrays?

**Comment by avik-pal** [comment]
Yes, it is a bug. #761 should fix this.

**Comment by avik-pal** [comment]
Closing this as it should be fixed now.

**Comment by GantZA** [comment]
This bug is back, but I don't know why. The master version on github has the correction you made but the one I get when I use `add Flux` doesn't have the fix. I also downloaded the source of 0.8.3 from https://github.com/FluxML/Flux.jl/releases and the fix isnt there. 

Should the fix be on the latest version?
